"""followers

Revision ID: 148bbe800f4e
Revises: bdbf50e59e50
Create Date: 2020-07-15 12:09:27.186120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148bbe800f4e'
down_revision = 'bdbf50e59e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
